theme: jekyll-theme-hacker

title: [Trocar código para conquistar amigos]
description: [Códigos para: (i) Software educativo, (ii) Treinamento de Xadrez, (iii) Cálculo numérico, (iv) Mineração de dados]
